# Continuous integration for Angular
name: Angular GitHub CI / CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]
jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
     
     steps: 
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup
        run: npm ci

      - name: Lint
        run:
          npm run lint

      - name: Build
        run:
          npm run build -- --prod

      - name: Test
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

      - name: Cypress Tests
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true      
